### ISSUE TITLE
Is there anything different planned for this repository?

### ISSUE THREAD

**Issue by millionart** [Cesio137/ALS_Replicated#1]
I'm working on a game using the old repository, and while there are still a few minor bugs, thank you very much for your efforts. I'm interested to know what prompted you to recreate the repository instead of continuing development based on the original content?

**Comment by nathancmiguel** [comment]
> I'm working on a game using the old repository, and while there are still a few minor bugs, thank you very much for your efforts. I'm interested to know what prompted you to recreate the repository instead of continuing development based on the original content?

- Full blueprint now, no need to compile.
- Plugin
- Fixed IA player focus
- Added support to enhancement input (UE5)
- Fixed spawn component error
