### ISSUE TITLE
Gamepad Controls are Broken

### ISSUE THREAD

**Issue by Digital33Studios** [Cesio137/ALS_Replicated#3]
Right Analog Stick Down direction causes interference with Perspective change.
No Analog Deadzones detected so player constantly moves.

Recommend Following these Guides to apply proper Controls:

https://www.youtube.com/watch?v=-j53TJD43u0
https://www.youtube.com/watch?v=CnFCa3sHHdc

**Comment by nathancmiguel** [comment]
Added dead zone now
